# Generated by Django 4.1.2 on 2022-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('create_time', models.DateTimeField(verbose_name='create time')),
                ('last_edit_time', models.DateTimeField(verbose_name='last edit time')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
